### PR TITLE
PlaySound Fix, 7.3 update, and FAQ fixup

### PR DESCRIPTION
**Pull request by brittyazel**
Fixes the PlaySound errors. There were a lit more than I initially thought, but I think I got them all

### CODE REVIEW

**Comment by AlexFolland** [comment]
This seems to be a duplicate of [pull request 37](https://github.com/SLOKnightfall/Ion-Core/pull/37).  What's the difference?

**Comment by brittyazel** [comment]
The PlaySound Errors fix. I didn't know how to do a pull request on only the changes since the prior pull request. 
I fixed 2 dozen or so playsound errors in this addon, as well as in the menu-bar, and status-bar addons that were causing errors. Someone over on Wowinterface made mention that clicking the "menu button" didn't bring up the menu anymore, and alas it was the same bug as the minimap button bug.

**Comment by brittyazel** [comment]
I made a couple more quick changes. I fixed a bug with the menubar having the "?" help menu peek through in certain circumstances. I also tweaked the mini-map Icon color to follow the "Lithium" naming scheme, mostly just for fun.

**Comment by brittyazel** [comment]
#Note the updated Ace3 libs were necessary due to the PlaySound errors above. I have not found any changes as part of the updated libs, and it feels quite refreshing to have modern libs linked. :-)

**Comment by brittyazel** [comment]
Another thing to note, is that there was an extra .toc file at the root of the Ion-Core repository, and it seemed to be a duplicate of the one found in the Ion directory. I removed it, as it seemed redundant, though perhaps it is necessary for packaging for Curse?

**Pull request closed without merging**
